language: cpp
sudo: false
install: true
dist: trusty

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages: 
          - g++-7
    env: COMPILER=g++-7
  - os: linux
    compiler: clang
    addons:
      apt:
        sources: 
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
        packages: 
        - clang-5.0
        - libstdc++-4.9-dev
    env: COMPILER=clang++-5.0
  - os: osx
    osx_image: xcode9.1
    compiler: clang
    env: COMPILER=clang++

script:
  - cd EnttPong
  - cmake -Wno-dev -Wno-deprecated ..
  - make -j3